logging:
  level:
    org:
      apache:
        poi:
          openxml4j:
            opc:
              OPCPackage: ERROR
server:
  port: 8085
spring:
  application:
    name: "ms-database-analysis"
  devtools:
    add-properties: false
  profiles:
    include: null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
jwt:
  json-exp-roles: "/roles"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8085"
general:
  file-type-report-generated: ".xlsx"
  sheet-name: "Errores"
headers:
  categoriesRules: No Nulos,Nulos,Tipo-variable,Tamaño,Minimos y Maximos, \
    Campos Duplicados,Diccionario,Comparacion-entre-columnas,Comparacion-Fechas, \
    orderColumnsRules,rangeWithWordRules,dateRangeRules,specificValuesRules,conditionalNonNullRule
routes:
  dictionary-common-names: "C:\\Projects\\GitHub\\Savia\\databases\\BD NOMBRES CIENTIFICOS CORREGIDA 2024 (completa).xlsx"
  file-path-report-generated: "C:\\Projects\\GitHub\\Savia\\Errors-"
